tests/samples/git.diff, unidiff/constants.py, unidiff/patch.py
When git-2.4 formats a patch containing an unaltered empty line it
puts an empty line ('\n') in the output. unidiff expects such lines
to have a leading space (' \n') and throws an exception when presented
with such patches.
This patch fixes parser to cope with this input and updates the git
test file so that it contains an empty line.
=> Improve support for git patches

unidiff/patch.py
Some patch files can contain more than one encoding. :(
=> Adding errors attribute to from_filename method

unidiff/patch.py
The processing for each hunk is currently O(N^2) causing patch
processing times to explode for patches that introduce a new file.
For example, on a 4GHz AMD CPU it takes over a minute to handle a
13,000 line patch file.
When the O(N^2) is replacd with an O(N) algorithm the same file can
be processed in half a second!
=> Optimize for large hunk sizes.

MANIFEST.in
In packaging this project for Fedora I noticed that the `tests/samples` directory is missing from tarballs published on PyPI. That means I can't run the tests as part of the build process.
This addition to `MANIFEST.in` should do the trick.
=> include test sample data in tarballs

tests/samples/sample3.diff, tests/samples/sample4.diff, tests/test_parser.py, unidiff/constants.py, unidiff/patch.py
Two changes here:
1. Treat line endings as an integral part of hunk lines, therefore preserving them.
2. Preserve the No newline at end of file markers so that parsed patches can be reproduced exactly by printing.
Please review.
=> A few changes to handling newlines

setup.py
Currently if you do `python setup.py install --root=somewhere` then you get a top-level package called `tests`:
```
[...]
creating somewhere/usr/lib/python2.7/site-packages/unidiff
copying build/lib/unidiff/__init__.py -> somewhere/usr/lib/python2.7/site-packages/unidiff
copying build/lib/unidiff/errors.py -> somewhere/usr/lib/python2.7/site-packages/unidiff
copying build/lib/unidiff/constants.py -> somewhere/usr/lib/python2.7/site-packages/unidiff
copying build/lib/unidiff/patch.py -> somewhere/usr/lib/python2.7/site-packages/unidiff
creating somewhere/usr/lib/python2.7/site-packages/tests
copying build/lib/tests/__init__.py -> somewhere/usr/lib/python2.7/site-packages/tests
copying build/lib/tests/test_hunks.py -> somewhere/usr/lib/python2.7/site-packages/tests
copying …
```
=> don't install tests as a top-level package

tests/test_parser.py, unidiff/patch.py
this will look for string-like inputs, and parse them correctly into patch sets, allowing the syntax in 
https://github.com/matiasb/python-unidiff/issues/26
I'm happy to update examples/tests or otherwise improve this if you feel iffy about the implementation or behavior.👍
=> accept strings in constructor

tests/samples/git.diff, tests/samples/sample5.diff, tests/samples/sample6.diff, tests/samples/sample7.diff, tests/test_parser.py, unidiff/constants.py, unidiff/patch.py
Now lines below are also parsed and added to `PatchedFile`
```
diff --git a/added_file b/added_file
new file mode 100644
index 0000000..9b710f3
```
Additionally unidiff now better parses empty lines within hunks (some editors may remove trailing spaces which is not a problem for GNU `patch`)
Also conversion to string now produces same diff as it was originally. This might be helpful for those who needs validating diffs/remove some irrelevant info/fix empty lines in hunks and save diff back to file.
=> Implement parsing of lines with extended patch info

unidiff/patch.py
Fixes #58 (_Allow gracefully removing lines from a patch_) Previously the list of source/target lines and the number of added/removed lines were maintained during `.append()`. However, this mean that reassignments, pops, deletions, etc. did not correctly propagate.
The simplest solution is just to recalculate those members as needed.
This patch maintains the current API exactly, except that badly-behaved user code could have modified these members manually, which would now throw an exception.
=> Calculate hunk metrics as needed, to allow hunk modification

README.rst
The Python2 has stopped maintenance since the beginning of this year.
The README docs is out-of-date for it using py2, thus this PR upgrades it to Python3.
All code in the README are carefully checked to ensure they run correctly under py3.
Additionally, add syntax highlight for inline-code (such as variable/class names).
=> Upgrading README to python3 version

unidiff/patch.py
During parsing we're currently match against an empty line first and if that fails, try to match against a non-empty line. This is inefficient because most lines in diffs contain some content, thus we end up with two regex matches for most lines.
Swapping the regex match operations makes this more efficient for the general case, because only one match would be performed. In fact, the only case when RE_HUNK_EMPTY_BODYLINE makes a difference is when the line consists only of newline characters.
This optimization results in unidiff binary being faster by around 10% for large textual diffs.
=> Optimize hunk parsing

bin/unidiff, tests/test_parser.py, unidiff/patch.py
Some refactoring on top of #68.
Thanks p12tic!
=> Added option to only parse diff metadata

tests/test_parser.py, unidiff/patch.py
In my use case I'm using this great library to figure out how code has moved around. For this use case the only thing that matters is the hunk positions and sizes. Unfortunately full diff parsing uses large amount of memory and is slow and there's no way to disable it in this library.
This PR adds a new option `only_hunk_positions` that enables a fast code path that only parses the hunk headers, only does minimal parsing of the line contents and does not store them. Enabling this option results in ~20 times less memory use and 6 times faster diff parsing on Python 3.6 (2.5 times on Python 2.7).
=> Add an option to parse only hunk positions

unidiff/patch.py
This fixes a bug where, in a diff where the first change is a binary file, unidiff errors with
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_5/lib/python3.9/site-packages/unidiff/patch.py", line 538, in from_filename
instance = cls(f)
File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_5/lib/python3.9/site-packages/unidiff/patch.py", line 421, in __init__
self._parse(data, encoding=encoding, metadata_only=metadata_only)
File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_5/lib/python3.9/site-packages/unidiff/patch.py", line 520, in _parse
patch_info.append(line)
AttributeError: 'NoneType' object has no attribute 'append'
```
Reproduction steps:
```sh
$ echo "package main\nfunc main(){}" > …
```
=> Fix an error when the first change is a binary

tests/samples/git_rename.diff, tests/test_parser.py, unidiff/constants.py, unidiff/patch.py
Supersedes #76 and fixes both issues described in #77.
=> Fix a few issues with git renames handling

unidiff/patch.py
While debugging my own code I found it useful to have more insight into what types I was getting, so I added type hints. These are in the Python 2 friendly style, using comments. These are picked up by type hinters, linters, language servers, etc. but don't break compatibility with Python 2 like the colon syntax does.
Example:
=> Add type hints

README.rst, tests/samples/git_cr.diff, tests/test_parser.py, unidiff/patch.py
This is to add the `newline` parameter to `PatchSet::from_filename`. 
This was originally submitted as pull request #83 that contains two changes
1. add the `newline` parameter and 
2. add Github Actions configuration file. 
This proposal only contains the changes for change 1 in the above.  Change 2 will be submitted as a separate proposal following this one.
=> added newline parameter to PatchSet::from_filename and test case with test diff file

tests/samples/sample8.diff, tests/test_parser.py, unidiff/constants.py, unidiff/patch.py
Hello. I've faced the issue today in ClickHouse/ClickHouse#32911 that the empty new files aren't fetched. It means, our CI may not work correctly for some other edge cases.
Here I've implemented the parsing for such diffs and tests for them:
```diff
diff --git a/boo.bin b/boo.bin
new file mode 100644
index 0000000..ae000000
```
The PR fixes #19
=> Fix issue #19: emtpy new git file

tests/samples/git_no_prefix.diff, tests/test_parser.py, unidiff/constants.py
Make git prefix optional when parsing a git header.
Related to #81. Still requiring support to allow custom prefixes, but fixes issue when --no-prefix is set.
=> Make git prefix optional in regex

unidiff/constants.py
`\s` isn't a valid backslash escape for a normal Python escape, which ends up
"working" since the `\s` gets preserved verbatim.
However, the invalid backslash escape can break other tools that process Python
source code, notably `pytest`s assertion rewriting.
=> Raw strings for RE_BINARY_DIFF

tests/samples/git_delete.diff, tests/test_parser.py, unidiff/constants.py
RE_DIFF_GIT_DELETED_FILE and RE_DIFF_GIT_NEW_FILE match on a complete
line pattern 'r^$' so including `\n` in the pattern leads to the pattern
not matching. Remove the `\n`.
=> Remove newline from RE_DIFF_GIT_{DELETED,NEW}_FILE

tests/samples/git_filenames_with_spaces_prefix.diff, tests/test_parser.py, unidiff/constants.py, unidiff/patch.py
Stash (Bitbucket) uses `src://` and `dst://` instead of `a` and `b`
Add a new handler for handling custom prefixes which allows for spaces.
=> Fix issue with spaces in filename when using custom prefix
